#!/bin/bash
for compName in $*
do
    (lerna exec --scope @uiw/react-$compName -- tsbb watch) &                             # lib:watch
    (lerna exec --scope @uiw/react-$compName -- compile-less -d src -o esm --watch)       # lib:css:watch
    # lerna exec --scope @uiw/react-$compName -- compile-less -d src -o lib --combine=dist.css
    # lerna exec --scope @uiw/react-$compName -- compile-less -d src -o esm
    # lerna exec --scope @uiw/react-$compName -- tsbb build --target react
    lerna bootstrap --hoist --scope @uiw/react-$compName
done

