name: Deploy Website
on:
  push:
    branches:
      - v5
    paths-ignore:
      # - '.github/**/*.yml'
      - '.gitignore'
      - '.gitpod.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14

    - run: npm install
    - run: npm run hoist

    - run: npm run build
    - run: npm run bundle
    - run: npm run b:website
    - run: npm run coverage

    - run: cp -rp packages/uiw/dist/*js website/build
    - run: cp -rp packages/uiw/dist/*css website/build

    - name: Generate Contributors Images
      uses: jaywcjlove/github-action-contributors@main
      with:
        filter-author: (renovate\[bot\]|actions-user|renovate-bot|dependabot\[bot\])
        output: ./website/build/CONTRIBUTORS.svg
        avatarSize: 42


    - name: get tag version
      id: tag_version
      uses: jaywcjlove/changelog-generator@v1.5.0

    - name: Deploy to uiwjs.github.io Repo
      uses: peaceiris/actions-gh-pages@v3
      with:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: '[${{steps.tag_version.outputs.tag}}] ${{ github.event.head_commit.message }}'
        personal_token: ${{ secrets.PERSONAL_TOKEN_UIW }}
        publish_dir: ./website/build
        publish_branch: v5
        external_repository: uiwjs/uiwjs.github.io